server:
  port: 8082
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example
    username: example_ddl
    password: example_ddl
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/example
    user: example_ddl
    password: example_ddl
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG